#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Burndown chart:"
  echo "    burndown"
  echo "      generate a textual burndown report"
  echo ""
  exit
}

[ "$action" = "burndown" ] && {
  python ${TODO_ACTIONS_DIR}/burndown.py "$TODO_FILE" "$DONE_FILE"
}
