for config_file (~/.bash/special/*.bash) source $config_file

if [[ ${OSTYPE#darwin} != $OSTYPE ]]; then
  source ~/.bash/special/os/macosx.zsh
elif [[ ${OSTYPE#linux} != $OSTYPE ]]; then
  source ~/.bash/special/os/linux.zsh
fi
